# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: pinger.proto for package 'pinger'

require 'grpc'
require 'pinger_pb'

module Pinger
  module PingerService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'pinger.PingerService'

      rpc :Ping, ::Pinger::Empty, ::Pinger::Pong
    end

    Stub = Service.rpc_stub_class
  end
end
