# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_proto.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("user_proto.proto", :syntax => :proto3) do
    add_message "user_proto.Empty" do
    end
    add_message "user_proto.GetUserReq" do
      optional :id, :int64, 1
    end
    add_message "user_proto.User" do
      optional :last_name, :string, 1
      optional :first_name, :string, 2
      optional :email, :string, 3
    end
    add_message "user_proto.Users" do
      repeated :users, :message, 1, "user_proto.User"
    end
  end
end

module UserProto
  Empty = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("user_proto.Empty").msgclass
  GetUserReq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("user_proto.GetUserReq").msgclass
  User = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("user_proto.User").msgclass
  Users = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("user_proto.Users").msgclass
end
