# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: user_proto.proto for package 'user_proto'

require 'grpc'
require 'user_proto_pb'

module UserProto
  module UserService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'user_proto.UserService'

      rpc :GetUsers, ::UserProto::Empty, ::UserProto::Users
      rpc :GetUser, ::UserProto::GetUserReq, ::UserProto::User
    end

    Stub = Service.rpc_stub_class
  end
end
