# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: user.proto for package 'proto'

require 'grpc'
require 'user_pb'

module Proto
  module UserService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'proto.UserService'

      rpc :GetUser, ::Proto::Empty, ::Proto::User
    end

    Stub = Service.rpc_stub_class
  end
end
