# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("user.proto", :syntax => :proto3) do
    add_message "proto.Empty" do
    end
    add_message "proto.User" do
      optional :name, :string, 1
    end
  end
end

module Proto
  Empty = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.Empty").msgclass
  User = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.User").msgclass
end
