FROM ruby:2.6.3

RUN apt-get update && \
  apt-get install -y \
  # NOTE: credentials.ymlを開く時にvimが必要なため
  vim

WORKDIR /app

ADD Gemfile .
ADD Gemfile.lock .
RUN bundle install -j4

COPY . /app

COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]

EXPOSE 3000
