version: '3'
services:
  app:
    build:
      context: .
      target: dev
    volumes:
      - .:/app
    tty: true
    ports:
      - "5300:5300"

networks:
  default:
    external:
      name: go_default