version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    volumes:
      - ./:/app:cached
    tty: true
    ports:
      - "50051:50051"
    environment:
      - GRPC_SERVICE_PORT=50051

networks:
  default:
    external:
      name: go_default