version: '3'
services:
  app:
    build:
      context: .
      target: dev
    volumes:
      - ./:/app:cached
    tty: true
    ports:
      - "50051:50051"
    environment:
      - environment=development
      # - environment=production
      - GRPC_SERVICE_PORT=50051
    env_file:
      - .env

networks:
  default:
    external:
      name: go_default