# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: user.proto for package 'pb.user'

require 'grpc'
require 'user_pb'

module Pb
  # module User
    module UserService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'pb.user.UserService'

        rpc :GetUsers, ::Pb::User::Empty, ::Pb::User::Users
        rpc :GetUser, ::Pb::User::GetUserReq, ::Pb::User::User
      end

      Stub = Service.rpc_stub_class
    end
  # end
end
