# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("user.proto", :syntax => :proto3) do
    add_message "pb.GetUsersReq" do
    end
    add_message "pb.GetUserReq" do
      optional :id, :int64, 1
    end
    add_message "pb.User" do
      optional :last_name, :string, 1
      optional :first_name, :string, 2
      optional :email, :string, 3
    end
    add_message "pb.Users" do
      repeated :users, :message, 1, "pb.User"
    end
  end
end

module Pb
  GetUsersReq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.GetUsersReq").msgclass
  GetUserReq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.GetUserReq").msgclass
  User = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.User").msgclass
  Users = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.Users").msgclass
end
