# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: smarthr/crew.proto for package 'smarthr'

require 'grpc'
require 'smarthr/crew_pb'

module Smarthr
  module Crews
    # これつけたら動かなそう
    # import "smarthr/department.proto";
    #
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'smarthr.Crews'

      rpc :GetCrew, ::Smarthr::Empty, ::Smarthr::Crew
    end

    Stub = Service.rpc_stub_class
  end
end
