version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile.dev
    command: bundle exec rails s -b '0.0.0.0'
    stdin_open: true
    tty: true
    ports:
      - '30000:3000'
    volumes:
      - .:/app:cached
      - /var/tmp
      - sockets:/app/tmp/sockets
    environment:
      - GRPC_SERVICE_NAME=go_app_1
      - GRPC_SERVICE_PORT=50051
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: grpc_development
      MYSQL_ROOT_PASSWORD: finder0501
      TZ: "Asia/Tokyo"
    ports:
      - '13306:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
  sockets:

networks:
  default:
    external:
      name: go_default