version: '3'
services:
  app:
    build:
      context: .
      dockerfile: .
    command: rails s -b '0.0.0.0'
    stdin_open: true
    tty: true
    ports:
      - '3000:3000'
    volumes:
      - .:/app:cached
      - /var/tmp
      - sockets:/app/tmp/sockets

volumes:
  sockets:
