version: '3'
services:
  app:
    build:
      context: .
      dockerfile: .
    command: rails s -b '0.0.0.0'
    stdin_open: true
    tty: true
    ports:
      - '3000:3000'
    volumes:
      - .:/app:cached
      - /var/tmp
      - sockets:/app/tmp/sockets
    environment:
      - GRPC_SERVICE_NAME=go_app_1
      - GRPC_SERVICE_PORT=5300

volumes:
  sockets:

networks:
  default:
    external:
      name: go_default